services:
  agent:
    build: 
      context: ./agent 
      dockerfile: Dockerfile
    ports: 
      - '5000:5000'
    env_file:
      - ./agent/.env
    volumes:
      - ./agent:/app
    networks:
      - agentic
    depends_on:
      - backend 

  backend:
    build: 
      context: ./backend 
      dockerfile: Dockerfile
    ports: 
      - '3000:3000'
    env_file:
      - ./backend/.env
    volumes:
      - ./backend:/app
    networks:
      - agentic
    depends_on:
      - redis

  redis:
    image: redis:latest
    ports:
      - '6379:6379'
    networks:
      - agentic

networks:
  agentic:
    driver: bridge
